# Project-level partial overrides of Coding Standards
version: 1
project: EXA
language: csharp
valid_until: 2026-03-31
adr: ADR-0000
rules:
  core:
    test.coverage.min: 0.80   # SHOULD in Core; PJ raises/lowers within allowed range
  csharp:
    analyzer.stylecop: warning
    warnings.as_errors: false
