name: csharp-check
on: [push, pull_request]
jobs:
  build-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'
      - name: Restore
        run: dotnet restore
      - name: Build (warnings as errors optional via overrides)
        run: dotnet build --no-restore
      - name: Test
        run: dotnet test --no-build --logger trx
